# Generated by Django 4.0.4 on 2022-04-30 09:41

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Названия')),
                ('image', models.ImageField(blank=True, upload_to='Product/photo/%Y/%m/%d', verbose_name='Фото')),
                ('description', models.TextField(verbose_name='Описание')),
                ('new_price', models.FloatField(verbose_name='Новая цена')),
                ('old_price', models.FloatField(verbose_name='Старая цена')),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2022, 4, 30, 9, 41, 39, 437868, tzinfo=utc), verbose_name='Дата публикации')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
