# Generated by Django 4.0 on 2022-05-05 10:17

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('email', models.EmailField(max_length=100)),
                ('profession', models.CharField(max_length=100, verbose_name='Профессия')),
                ('company', models.CharField(max_length=100, verbose_name='Компания')),
                ('message', models.TextField(verbose_name='Текст')),
                ('image', models.ImageField(blank=True, upload_to='Customer/%Y/%m/%d', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='new_price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Новая цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Старая цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 5, 10, 17, 17, 959022, tzinfo=utc), verbose_name='Дата публикации'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('email', models.EmailField(max_length=100)),
                ('website', models.CharField(max_length=150)),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='Дата публикации')),
                ('image', models.ImageField(blank=True, upload_to='Comment/%Y/%m/%d', verbose_name='Фото')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
