# Generated by Django 4.0 on 2022-05-05 11:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_customer_alter_product_new_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Вы автор'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 5, 11, 29, 21, 190557, tzinfo=utc), verbose_name='Дата публикации'),
        ),
    ]
