# Generated by Django 4.0 on 2022-05-06 08:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_comment_is_admin_alter_comment_website_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 6, 8, 35, 14, 215109, tzinfo=utc), verbose_name='Дата публикации'),
        ),
    ]
