# Generated by Django 4.0 on 2022-05-06 15:27

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_product_pub_date_alter_review_image_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='watch',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Просмотры'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 6, 15, 27, 54, 56826, tzinfo=utc), verbose_name='Дата публикации'),
        ),
    ]
